<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFAka1ue\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFAka1ue/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFAka1ue.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFAka1ue\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFAka1ue\App_KernelDevDebugContainer([
    'container.build_hash' => 'FAka1ue',
    'container.build_id' => '0efc1e7b',
    'container.build_time' => 1635959099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFAka1ue');
